### ISSUE TITLE
IOTEUR symbol for the ticker

### ISSUE THREAD

**Issue by ioiobzit** [bitfinexcom/bitfinex-api-node#175] opened 2018-01-03 15:38 UTC
Hello,

whether I'm unable to find the IOTEUR symbol for the ticker, or it is missing.

Could you please add it to the API, also the BTCEUR symbol would be nice.

All the best,
Antonio

**Comment by f3rno** [comment] 2018-01-03 16:11
It is not missing, but needs to be prefixed with 't', like `tIOTEUR`. Check the referenced PR for an example :)

**Comment by f3rno** [comment] 2018-01-06 00:43
Closing as duplicate of #176

**Closed by f3rno** 2018-01-06 00:43 UTC
