### ISSUE TITLE
Is there a way to map symbols?

### ISSUE THREAD

**Issue by npomfret** [bitfinexcom/bitfinex-api-node#462] opened 2019-02-25 23:02 UTC
The reports UI maps my old (pre-fork) tBCHUSD trades and displays them as BCH/USD.  The same goes for new tBABUSD trades which are also mapped to BCH/USD.

Is there an API call that I can use to provide this mapping?

**Comment by f3rno** [comment] 2019-02-26 15:40
Duplicate of https://github.com/bitfinexcom/bfx-api-node-rest/issues/19

**Closed by f3rno** 2019-02-26 15:40 UTC
