### ISSUE TITLE
Checksum errors

### ISSUE THREAD

**Issue by davidjirovec** [bitfinexcom/bitfinex-api-node#511] opened 2020-01-29 22:06 UTC
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Checksum errors appear randomly. Sometimes it can take days of runtime to happen, but it shouln't happen at all, right?

```
Mon, 27 Jan 2020 16:54:16 GMT bfx:examples:ws2_ob_checksum open
Mon, 27 Jan 2020 16:54:18 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 1846761323
Mon, 27 Jan 2020 16:54:18 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 1931307502
Mon, 27 Jan 2020 16:54:18 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 549474894
Mon, 27 Jan 2020 16:54:18 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1934838570
Mon, 27 Jan 2020 16:54:19 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 537105635
Mon, 27 Jan 2020 16:54:19 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 896375196
Mon, 27 Jan 2020 16:54:19 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1311561612
Mon, 27 Jan 2020 16:54:19 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1827489479
Mon, 27 Jan 2020 16:54:19 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 2071535722

...

Tue, 28 Jan 2020 07:18:30 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1124314668
Tue, 28 Jan 2020 07:18:30 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -602742618
Tue, 28 Jan 2020 07:18:30 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 1964069441
Tue, 28 Jan 2020 07:18:30 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1502238394
Tue, 28 Jan 2020 07:18:30 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 586684925
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 859199825
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 23471103
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -70162690
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 2085698518
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1017291853
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -298827506
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 1255504028
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 1891849048
Tue, 28 Jan 2020 07:18:31 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 1510463000
Tue, 28 Jan 2020 07:18:32 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -834422132
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum error tBTCUSD:R0:100 OB checksum mismatch: got -1400848629, want -1265276067
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum error tBTCUSD:R0:100 OB checksum mismatch: got 1188429631, want -1833259737
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum error tBTCUSD:R0:100 OB checksum mismatch: got 602120660, want -326847754
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum error tBTCUSD:R0:100 OB checksum mismatch: got -422903833, want -264548176
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum error tBTCUSD:R0:100 OB checksum mismatch: got 930459460, want -2068145465
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum error tBTCUSD:R0:100 OB checksum mismatch: got -140089540, want -66646570
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum error tBTCUSD:R0:100 OB checksum mismatch: got 25330788, want -1364977627
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum error tBTCUSD:R0:100 OB checksum mismatch: got 1813924277, want 1898202382
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -375022420
Tue, 28 Jan 2020 07:18:33 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 1900550324
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -393593847
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 1886951354
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1517204051
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -807542396
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -186071411
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1644208962
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -1797628273
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -489818669
Tue, 28 Jan 2020 07:18:34 GMT bfx:examples:ws2_ob_checksum recv valid cs for tBTCUSD:R0:100 -689604369

```

#### Steps to reproduce
Run `examples/ws2/ob_checksum.js` and wait.

**Comment by JacobPlaster** [comment] 2020-01-30 07:06
Hey @davidjirovec, we have just discovered this issue ourselves as well. The checksum failure  is caused when a user submits a really small order which gets formated into scientific notation `1-e8` ect...

We are working on a fix now

**Comment by davidjirovec** [comment] 2020-01-30 15:15
Thank you. Anyway, why is there so complicated number formatting? I did not find any mention of this in api documentation, there is just
```
OB_CHECKSUM

131072

Enable checksum for every book iteration. Checks the top 25 entries for each side of book. Checksum is a signed int.
```
More detailed description is here https://blog.bitfinex.com/api/bitfinex-api-order-books-checksums/
but still no details on number formatting.

**Comment by JacobPlaster** [comment] 2020-02-03 12:37
Well the problem is on the client end of things, the bitfinex websocket sends the orderbook decimals in standard non-complex string format i.e "0.000000001" but then javascript converts that to "1e-8" when attempting to compare the checksum which causes the failure. The best way to do it (an how we do it with the go client) is to just use the raw strings that the websocket passes down to us and avoid converting to a number.

**Comment by f3rno** [comment] 2020-02-25 19:15
Fixed by https://github.com/bitfinexcom/bitfinex-api-node/pull/516

**Closed by f3rno** 2020-02-25 19:15 UTC
