### ISSUE TITLE
How to change an order -> cancel/open -> "not enough exchange balance"

### ISSUE THREAD

**Issue by algotek** [bitfinexcom/bitfinex-api-node#128] opened 2017-09-27 18:48 UTC
The cancel/open , especially with multi-op command is not working, and end up in a " not enough balance " error.
 Please suggest something else, or solve the "not enough exchange balance " error.

**Comment by algotek** [comment] 2017-09-27 19:19
Just to clarify, the cancel is successful, the 'not enough balance' come at the re-open phase.

**Comment by algotek** [comment] 2017-09-28 06:32
Error confirmed here #124

**Comment by f3rno** [comment] 2018-01-03 12:18
I'm closing this as a duplicate of #141; although it's specific to the multi-op endpoint, the issue is general and on the server.

**Closed by f3rno** 2018-01-03 12:18 UTC
