### ISSUE TITLE
websocket 2 repeating open / auth messages 

### ISSUE THREAD

**Issue by npomfret** [bitfinexcom/bitfinex-api-node#464] opened 2019-02-28 09:33 UTC
The following code is resulting in repeating _open_ messages, followed by duplicate _auth_ messages and eventually a rate limit error.  I've copied it (more or less) from this site.  Can't see what's wrong - any ideas?

```
    async start(keys) {
        const {apiKey, secret} = keys;

        const bfx = new BFX({
            apiKey,
            apiSecret: secret,
            ws: {
                autoReconnect: true,
                seqAudit: true,
                packetWDDelay: 10 * 1000
            }
        });

        const ws = bfx.ws();

        ws.on('error', (err) => console.error(`${new Date().toISOString()} bfx ws error`, err));

        ws.on('open', () => {
            console.log(`${new Date().toISOString()} bfx ws open`);
            ws.auth();
        });

        const authPromise = new Promise((resolve, reject) => {
            ws.once('auth', () => {
                console.log(`${new Date().toISOString()} bfx ws authenticated`);
                resolve();
            });
        });
        ws.open();
        await authPromise;
```

Timestamped output:

```
2019-02-28T09:26:57.814Z bfx ws open
2019-02-28T09:26:57.846Z bfx ws authenticated
2019-02-28T09:27:08.027Z bfx ws open
2019-02-28T09:27:08.060Z bfx ws error: [object Object] { event: 'error', msg: 'auth: dup', code: 10100 }
2019-02-28T09:27:18.228Z bfx ws open
2019-02-28T09:27:18.271Z bfx ws error: [object Object] { event: 'error', msg: 'auth: dup', code: 10100 }
2019-02-28T09:27:28.530Z bfx ws open
2019-02-28T09:27:28.570Z bfx ws error: Error: auth failed: rate: limit (FAILED) Error: auth failed: rate: limit (FAILED)
    at WSv2._handleAuthEvent (<myapp>bitfinex-api-node/lib/transports/ws2.js:1054:19)
    at WSv2._handleEventMessage (<myapp>bitfinex-api-node/lib/transports/ws2.js:982:19)
    at WSv2._onWSMessage (<myapp>bitfinex-api-node/lib/transports/ws2.js:550:12)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (<myapp>bitfinex-api-node/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (<myapp>bitfinex-api-node/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (<myapp>bitfinex-api-node/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (<myapp>bitfinex-api-node/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (<myapp>bitfinex-api-node/node_modules/ws/lib/Receiver.js:139:10)
    ...
2019-02-28T09:27:38.757Z bfx ws open
2019-02-28T09:27:38.786Z bfx ws error: [object Object] { event: 'error', msg: 'auth: dup', code: 10100 }
2019-02-28T09:27:38.787Z bfx ws error: Error: auth failed: rate: limit (FAILED) Error: auth failed: rate: limit (FAILED)
    at WSv2._handleAuthEvent (<myapp>bitfinex-api-node/lib/transports/ws2.js:1054:19)
    at WSv2._handleEventMessage (<myapp>bitfinex-api-node/lib/transports/ws2.js:982:19)
    at WSv2._onWSMessage (<myapp>bitfinex-api-node/lib/transports/ws2.js:550:12)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (<myapp>bitfinex-api-node/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (<myapp>bitfinex-api-node/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (<myapp>bitfinex-api-node/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (<myapp>bitfinex-api-node/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (<myapp>bitfinex-api-node/node_modules/ws/lib/Receiver.js:139:10)
    ...
2019-02-28T09:27:48.953Z bfx ws open
2019-02-28T09:27:48.983Z bfx ws error: [object Object] { event: 'error', msg: 'auth: dup', code: 10100 }
```

**Comment by f3rno** [comment] 2019-03-01 15:19
Use:

```
        ws.once('open', () => {
            console.log(`${new Date().toISOString()} bfx ws open`);
            ws.auth();
        });
```

(note `.once`), since you have `autoReconnect: true` and it automatically re-auths on reconnect.

I'm closing this as it is a duplicate of https://github.com/bitfinexcom/bitfinex-api-node/issues/465

**Closed by f3rno** 2019-03-01 15:19 UTC
