### ISSUE TITLE
Order ID in Trades WS v2 Public Channel and R0 OB (Raw Order Book)

### ISSUE THREAD

**Issue by Daimakaimura** [bitfinexcom/bitfinex-api-node#326] opened 2018-05-09 05:54 UTC
Hello, I am trying to match the Trades in the public channel with the R0 OB updates but it appears that there is no way to match the public trade item with the OB r0 update as the public trade item doesnt include the order_id. Is there a way to do that?

**Comment by f3rno** [comment] 2018-05-09 13:49
@Daimakaimura no, only trades on channel 0 (your trades) contain the order ID; public trade channels do not include it.

**Comment by roderickObrist** [comment] 2018-05-10 23:09
@Daimakaimura, I've been working on this for quite some time.
I have subscribed to both "book:R0" and "trades" and maintained an local copy of the order book and tried to line up the "te" with what's open. Here's what I've learnt so far

1. "te" will come before the equivalent order book update (sometimes up to 1-2 seconds, or 10-30 messages)
2. Either I have no idea what I'm doing or Bitfinex has 1-2% hidden orders (seems massive)
3. The presence of hidden orders makes this an inexact science
4. The prices don't need to match exactly (I've noticed that the trade price and the equivalent order book price can vary up to $0.000018)
5. The advertised order of the trades does not always match the age of the order (this implies that it's not always the top of book that get's matched first, but I really have no idea)
6. Sometimes the trade ID's are incremental, sometimes they are not (which has me wondering if all trades are advertised)

I would love someone from the Bitfinex team to tell me where I'm right and where I'm wrong because I'm new at this

**Comment by Daimakaimura** [comment] 2018-05-11 05:49
@roderickObrist, indeed that is what I had in mind. The reason I was trying to match the public trades channel messages with the R0 updates is because I realised that OB updates come too late for me. In my case the delay between the Trade (te msg) and the corresponding R0 update is around 100-200 ms. Much less than in your case but still big enough to render my strategy useless. Regarding the hidden orders, not sure if all that 1-2%  is hidden, take into account that several kind of orders will not get into the order book despite they are not hidden (like FOKs). I concur that it will be nice that someone from Bitfinex could provide some insight around these issues.

**Comment by roderickObrist** [comment] 2018-05-13 10:35
@Daimakaimura , Thanks for the reply.

I'm not saying that all "te" is 1-2s ahead at all times, just on extreme cases. Some tips I can give you if you're trying to reduce lag:
1. Try to find out which geolocation the bitfinex ws server is, and get AWS in the same data center. This can reduce your information lag by up to 200 ms, and your order lag by the same amount.
2. Don't use the REST API, every time rest API makes a request you are talking about a new TCP/IP socket and a SSL handshake etc, a websocket will make this once so you're cocked and ready to go.

In regards to FOKs, I thought they were on the taker side of a trade, thus never entering the orderbook.

My understanding is that every trade has a maker (limit or hidden) and a taker (FOK/market/matching limit). If there is no liquidity in the orderbook for a certain trade, then the taker must be a hidden order.

**Comment by f3rno** [comment] 2018-08-29 14:28
Closing as the original question has been answered; @roderickObrist I can confirm that this is an inexact science given the fact that we allow hidden orders :slightly_smiling_face: As for the lag & optimization suggestions, all are spot on (and in the case of REST delays, common knowledge)

**Closed by f3rno** 2018-08-29 14:28 UTC
