### ISSUE TITLE
Calling trades in v2 returns no data

### ISSUE THREAD

**Issue by alinberce** [bitfinexcom/bitfinex-api-node#113] opened 2017-09-13 10:31 UTC
I did not manage to see proper documentation of the new beta API calls so I am trying to get the history of trades (https://bitfinex.readme.io/v2/reference#rest-auth-trades-hist) which is more of a trial and error so far.

I did something like this:

   ```
 var start = new Date();
    start.setDate(start.getDate() - 365);

    start = start.getTime();
    var end = new Date().getTime();

   var currency='BTCUSD'
   var limit = 100

 bfx.makeAuthRequest('/auth/r/trades/t' + currency + '/hist', { start, end, limit }, function (err, response) {
   //response is always array of 0 length
 });
```
I tried playing with start, end values (seconds, 0, millis, unix, switched between start and end values) but no matter what I've tried I always get a zero response.

**Comment by Tetradeca** [comment] 2017-09-16 02:14
Do you mind trying on [this fork](https://github.com/HyperCubeProject/bitfinex-api-node)? If it works for you it might make @robertkowalski consider it ;D

**Comment by alinberce** [comment] 2017-09-16 09:12
@Tetradeca how can I add the fork to my project? Thank you.

**Comment by Tetradeca** [comment] 2017-09-16 18:06
You can either clone it and use [npm link](https://docs.npmjs.com/cli/link), or you could try uninstalling your current `bitfinex-api-node` package and doing

    npm install HyperCubeProject/bitfinex-api-node

**Comment by vire** [comment] 2017-12-09 14:14
I have similar problem with vanila call to the trades history API, it does not take into account the start/end query param nor body content :/

**Comment by f3rno** [comment] 2017-12-14 18:08
@vire can you share the snippet that makes the call?

**Comment by vire** [comment] 2017-12-14 19:23
@f3rno hmm surprisingly I've realized, that the problem was on the API v2 side, they just don't return a meaningful response.

I can't request historical orders just 72 hours ago I guess..

**Comment by JureVI** [comment] 2017-12-21 08:24
I've managed to make it work. Check the requests they make in their web app. When they're calling the endpoint they also include
```
{"_bfx":1}
```
in the request body. It's not bullet proof because the request body is undocumented, but it works.

**Comment by f3rno** [comment] 2017-12-21 18:00
@JureVI That shouldn't be needed, it looks like an internal flag for the frontend. I'm closing this issue as it isn't a problem in the library itself. Maybe the lag spikes over the last few weeks had something to do with it?

@vire if you're still seeing that limitation on historical orders, open up another issue w/ reproducible info and I'll take a look.

**Closed by f3rno** 2017-12-21 18:00 UTC
