### ISSUE TITLE
Error 500 from endpoint: /v1/position/claim

### ISSUE THREAD

**Issue by avihai-developer** [bitfinexcom/bitfinex-api-node#93] opened 2017-08-21 21:25 UTC
I got Error 500 from this endpoint: /v1/position/claim

**Comment by Tetradeca** [comment] 2017-08-22 01:28
@robertkowalski I believe the issue comes from the fact the [`claim_position`](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/rest.js#L264) method of the v1 client only takes the `position_id` as a parameter where it should also require to pass an `amount`.

@avihai-developer You can use this in the meantime:

```js
rest.make_request('position/claim', { position_id, amount }, (err, data) => {
 // you should get your data here
})
```

**Comment by avihai-developer** [comment] 2017-08-22 05:14
I tried this buy i got the same error

**Comment by newbdez33** [comment] 2017-08-28 22:43
any update here?

**Comment by robertkowalski** [comment] 2017-08-29 12:11
thank you for your patience, fix was just merged with https://github.com/bitfinexcom/bitfinex-api-node/pull/96

**Comment by newbdez33** [comment] 2017-08-29 12:29
> Error: Key amount should be a decimal string.
Still does not work. 

I also tried 
> parseInt(amount)  => amount

Then I got error 
Error: 500

I guess it is a bug from bitfinex?

**Comment by robertkowalski** [comment] 2017-08-29 13:36
you are right, we found an issue on the server side and were able to reproduce

**Comment by robertkowalski** [comment] 2017-08-30 14:55
fix is rolled out tomorrow :)

**Comment by newbdez33** [comment] 2017-08-31 02:01
Great! loooking for it!

**Comment by avihai-developer** [comment] 2017-08-31 18:51
Any update?

**Comment by newbdez33** [comment] 2017-08-31 23:24
I believe claim is fine now. I tried to claim a no exists position and it returns 400 which is correct now.

**Comment by robertkowalski** [comment] 2017-09-05 10:50
yep, we rolled out the fix on thursday. should be fixed now.

@avihai-developer can you confirm?

**Comment by f3rno** [comment] 2017-12-14 18:09
I'll close this for now as it seems to be fixed, please re-open if it appears again.

**Closed by f3rno** 2017-12-14 18:09 UTC
