### ISSUE TITLE
Order onclose sporadically fires twice. 

### ISSUE THREAD

**Issue by joepegler** [bitfinexcom/bitfinex-api-node#368] opened 2018-08-06 20:28 UTC
Any idea why the order close callback might fire twice? It doesn't happen every time - the majority of the time it fires once as expected. Seems to happen randomly. 
```
            const o = new Order({
                cid: Date.now(),
                symbol: 't' + pair,
                amount: amount,
                type: Order.type.MARKET
            }, ws);
            o.registerListeners();
            o.submit().catch(reject);
            o.on('close', res => {
                 console.log(res); // sometimes logged twice
```

**Comment by f3rno** [comment] 2018-08-13 13:12
@joepegler Do you receive multiple `oc` packets? You can check by setting `process.env.DEBUG = '*'`

**Comment by DevRonin** [comment] 2018-08-18 12:28
Same issue:
On cancellation:

bitfinex:ws recv msg: [0,"oc",[15612263482,null,1534595130070,"tEOSUSD",1534595130247,1534595160130,2,2,"EXCHANGE LIMIT",null,null,null,0,"CANCELED",null,null,0.1,0,null,null,null,null,null,0,0,0,null,null,"API>BFX",null,null,null]] +1s

bfx:examples:ws2_orders order updated: [15612263482,null,1534595130070,"tEOSUSD",1534595130247,1534595160130,2,2,"EXCHANGE LIMIT",null,null,null,0,"CANCELED",null,null,0.1,0,null,null,null,null,null,0,null,0] +30s

bfx:examples:ws2_orders order updated: [15612263482,null,1534595130070,"tEOSUSD",1534595130247,1534595160130,2,2,"EXCHANGE LIMIT",null,null,null,0,"CANCELED",null,null,0.1,0,null,null,null,null,null,0,null,0] +0ms

**Comment by f3rno** [comment] 2018-08-29 15:36
@DevRonin can you confirm that you are seeing duplicate `oc` packets on the wire? Pass `'*'` as the debug config string & check the console for received messages

**Comment by f3rno** [comment] 2018-10-16 12:51
Closing as I'm unable to reproduce; if it happens again for anyone, please re-open

**Closed by f3rno** 2018-10-16 12:51 UTC
Labels: awaiting-response
