### ISSUE TITLE
Empty orderbook WS

### ISSUE THREAD

**Issue by tuloski** [bitfinexcom/bitfinex-api-node#387] opened 2018-09-02 21:26 UTC
Very often it happens that using WS and the orderbook, with:

```
this.ws = bfx.ws(2, {
  manageOrderBooks: true, // tell the ws client to maintain full sorted OBs
  transform: true // auto-transform array OBs to OrderBook objects
})
```

the bids or asks of the book are empty as the following:

`{"domain":null,"_events":{},"_eventsCount":0,"raw":false,"bids":[],"asks":[[0.014833,1,-348966],[0.014834,1,-13923.27456843],[0.014872,1,-11554.07531921],[0.014912,1,-10000],[0.015486,4,-311173.07261],[0.015684,1,-1000],[0.015873,1,-29769.03832663],[0.015954,1,-2320.119992],[0.016261,3,-20430],[0.016639,1,-2412.924791],[0.016725,1,-20613],[0.017035,1,-800],[0.017395,1,-2000],[0.017523,1,-2509.441783],[0.017809,2,-1680],[0.018185,1,-22495.37],[0.018209,1,-2000],[0.018351,1,-999],[0.018439,1,-900],[0.018506,1,-999],[0.018583,3,-20785],[0.018769,1,-2609.819454],[0.019203,1,-2000],[0.019358,2,-50480],[0.019595,1,-2000]]}`

What is happening?

**Comment by f3rno** [comment] 2018-09-05 07:59
Hmm, this is very strange. Can you share a complete code sample so I can reproduce?

**Comment by tuloski** [comment] 2018-09-09 21:13
@f3rno It's basically the example file about the orderbooks. I just subscribed to different books, so it happens more often, but it happens even with the subscription to a single orderbook.

**Comment by f3rno** [comment] 2018-10-16 12:56
Closing as I'm unable to reproduce, please re-open if you see it again

**Closed by f3rno** 2018-10-16 12:56 UTC
Labels: awaiting-response

**Comment by tuloski** [comment] 2018-10-29 18:46
I always see it. It is never gone.
It's there also with the ws manager.

To reproduce: subscribe to all books and try to access the first element of the orderbook (with manageOrderBooks: true,  transform: true)

**Comment by f3rno** [comment] 2018-10-30 11:28
I just did, several times, all OBs come in with populated `bids` and `asks` arrays. Is there anything unique about your setup? I ran the `ws2_manager.js` example with extra logging checking the length of the arrays.

**Comment by tuloski** [comment] 2018-10-30 11:34
When you get the OB, try to access the first element of the array. It will get the error sooner or later.
I'll try to cut the code I'm using and post it here.

**Comment by f3rno** [comment] 2018-10-30 12:02
Alright, reproduced after two minutes :+1: I'll investigate
