### ISSUE TITLE
Order Model instance can not get detail property when 'transform' === true

### ISSUE THREAD

**Issue by PerterPon** [bitfinexcom/bitfinex-api-node#280] opened 2018-04-06 16:43 UTC
env:
bitfinex-api-node: 2.0.0-beta
node: 8.11.1
OS: macOS 10.12.6

Here is my code, I tried, when `transform` set to `true`, I can't get order's status from Order Model instance.

```
import * as BFX from 'bitfinex-api-node';
import * as Order from 'bitfinex-api-node/lib/models/order';

const bfx = new BFX( {
    apiKey: "xxx",
    apiSecret: "xxx",

    ws: {
        autoReconnect: true,
        seqAudit: false,
        packetWDDelay: 10 * 1000
    }
} );

const ws = bfx.ws( 2, {
    transform: true // when I set this to true, error occurred
} );

ws.on( 'open', () => {
    ws.auth();
} );

ws.on( 'error', ( error ) => {
    console.log( error );
} );

ws.once( 'auth', () => {
    console.log( 'authenticated' );

    let closed = false;

    const o = new Order( {
        cid: Date.now(),
        symbol: 'tNEOUSD',
        price: 1,
        amount: 0.2,
        type: Order.type.EXCHANGE_LIMIT
    }, ws );

    o.registerListeners();

    o.on( 'update', function(){
        console.log( 'order update', o.serialize() );
    } );

    o.on( 'close', function(){
        console.log( 'order close', o.status );
    } );

    ws.submitOrder( o ).then( () => {
        console.log( 'order model: ', o );
    } );

} );

ws.open();
```

The log I console after `ws.submitOrder( o )` look like this:

```
order model:  Order {
  domain: null,
  _events: { update: [Function], close: [Function] },
  _eventsCount: 2,
  _maxListeners: undefined,
  cid: undefined,
  symbol: undefined,
  price: undefined,
  amount: undefined,
  type: undefined,
  ...
```

**Comment by f3rno** [comment] 2018-04-11 20:33
@PerterPon hmm, I can't reproduce, I checked out `v2.0.0-beta` & copy/pasted your code. Is this still happening? Was there anything else in the logs before that output? Try adding `process.env.DEBUG = '*';` to the top of your file

**Comment by f3rno** [comment] 2018-04-18 14:32
Closing due to inability to reproduce, please re-open if you encounter it again

**Closed by f3rno** 2018-04-18 14:32 UTC
