### ISSUE TITLE
Frequently get "not enough balance" error when I have enough balance

### ISSUE THREAD

**Issue by LRonHubs** [bitfinexcom/bitfinex-api-node#141] opened 2017-11-04 16:01 UTC
All my balances are in the "exchange" wallet and I'm only executing exchange limit orders.

Very frequently when using the PUSH API I receive this response from the server. I've started immediately submitting another PUSH call to Update Balances immediately afterwards to see whats up, and unfortunately I find that my balance is definitely high enough for the order.  I'm also only trading about 90% of the balance, and the balance on either side of the trade is enough to cover fees

I'm wondering if anyone else has run into this issue?

**Comment by levz0r** [comment] 2017-12-20 10:35
Same issue here...

**Comment by mvp83** [comment] 2017-12-31 14:29
same issue with Order Multi-OP orders.

For instance, open order: 
`send to Bitfinex: [0,"on",null,{"gid":1,"cid":3029456402370,"type":"EXCHANGE LIMIT","symbol":"tLTCUSD","amount":"-0.6000000000000001","price":"216.6","hidden":0, "postonly":1}]`

Answer:

`Got msg: [0,"n",[null,"on-req",null,null,[6707624719,null,3029456402370,"tLTCUSD",null,null,-0.6,-0.6,"EXCHANGE LIMIT",null,null,null,null,null,null,null,216.6,null,null,null,null,null,null,0,null,null],null,"SUCCESS","Submitting exchange limit sell order for 0.6000000000000001 LTC."]]`
`Got msg: [0,"on",[6707624719,1,3029456402370,"tLTCUSD",1514728238977,1514728239038,-0.6,-0.6,"EXCHANGE LIMIT",null,null,null,0,"ACTIVE",null,null,216.6,0,null,null,null,null,null,0,0,0]]`

Now, try Order Mulit-op:

`[0,"ox_multi",null,[["oc",{"id": 6707624719}],["on",{"gid":1,"cid":3029456402371,"type":"EXCHANGE LIMIT","symbol":"tLTCUSD","amount":"-0.6","price":"216.61","hidden":0, "postonly":1}]]]`

Answer:

`15:50:40:115: Got msg: [0,"n",[null,"oc-req",null,null,[6707624719,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null],null,"SUCCESS","Submitted for cancellation; waiting for confirmation (ID: 6707624719)."]]`
`15:50:40:165: Got msg: [0,"n",[null,"on-req",null,null,[null,null,3029456402371,"tLTCUSD",null,null,-0.6,-0.6,"EXCHANGE LIMIT",null,null,null,null,null,null,null,216.61,null,null,null,null,null,null,0,null,null],null,"ERROR","Invalid order: not enough exchange balance for -0.6 LTCUSD at 216.61"]]`
`15:50:40:165: Got msg: [0,"oc",[6707624719,1,3029456402370,"tLTCUSD",1514728238977,1514728239270,-0.6,-0.6,"EXCHANGE LIMIT",null,null,null,0,"CANCELED",null,null,216.6,0,null,null,null,null,null,0,0,0]]`


Maybe, system doesn't calc balance in time :(

**Comment by StyleShit** [comment] 2018-01-02 19:52
I also get this error. Websockets v2.
I think the problem is in the server coz it happens only sometimes for me. Most of the orders proceed successfully.

**Comment by mvp83** [comment] 2018-01-02 21:00
have same issue through web-interface when i try change a price in a order. So, it does not depend from API

**Comment by StyleShit** [comment] 2018-01-03 05:27
Can anyone refer someone from Bitfinex staff to this post?

**Comment by f3rno** [comment] 2018-01-03 12:17
@StyleShit that would be me 💃 

This is a server issue (not in bitfinex-api-node), and has to do with the delay between closing an order and the associated balance update. Specifically, if you close and open an order simultaneously via the `ox_multi` endpoint, your wallet balance does not update between the two operations. Duplicated here: https://github.com/bitfinexcom/bitfinex-api-node/issues/128

It has to do with the fact that balance calculations are queued and not instantaneous, so it's a bit of a server limitation. I'll check with the team to see if there is anything we can do.

**Comment by wickowicz** [comment] 2018-01-27 06:45
In this case I'm checking the wallet and recreating order with amount, which is in the wallet (or simple recreating order).

**Comment by serzhiio** [comment] 2018-02-11 15:13
@f3rno i'm also very often have a 5-10secs delay between close-create. And this thing makes me mad. Guys, i'm a market maker with $7.5M+ volumes. And thats not seriuos for such a big exchange to have balance update problems. Please do something.

**Comment by f3rno** [comment] 2018-02-28 18:07
Alright everyone, this should now be mitigated (in most cases) by a recent trading engine update. I'm closing it in the meantime, feel free to re-open if it becomes a problem again in the future. Please be aware we cannot prevent this in **all** cases, but it should be far less of a problem going forwards.

**Closed by f3rno** 2018-02-28 18:07 UTC

**Comment by gfijrb** [comment] 2019-11-07 14:49
Its meaning that your order less then in 20-25 equivalent usd or more then 200000 coins/tokens on some pairs.
