### ISSUE TITLE
Error `invalid pub seq #` after submitting an order

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#519] opened 2020-02-21 17:37 UTC
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
After submitting an order, the error `invalid pub seq #` is received.

The issue is due to a coding fault in retrieving the sequence number for `on-req` messages
https://github.com/bitfinexcom/bitfinex-api-node/blob/abbd3c1825aadaf37cc049366fc2c029e6c0c493/lib/transports/ws2.js#L353-L359

For `on-req` message, the sequence number should be retrieved from the last value of the array.
Here is an example:
```json
[
  0,
  "n",
  [
    1582304782.761,
    "on-req",
    null,
    null,
    [
      40223669041,
      null,
      1582304782748,
      "tBTCUSD",
      1582304782760,
      1582304782760,
      -0.001,
      -0.001,
      "EXCHANGE LIMIT",
      null,
      null,
      null,
      0,
      "ACTIVE",
      null,
      null,
      10100,
      0,
      0,
      0,
      null,
      null,
      null,
      0,
      null,
      null,
      null,
      null,
      "API>BFX",
      null,
      null,
      null
    ],
    null,
    "SUCCESS",
    "Submitting exchange limit sell order for -0.001 BTC."
  ],
  12
]
```

#### Steps to reproduce
- enable sequence numbers & verification with `{ seqAudit: true }`
- submit an order

##### Additional Notes:
fix: 
```js
    const seq = (
      (msg[0] === 0) &&
      (msg[1] !== 'hb') &&
      !(msg[1] === 'n' && (msg[2][1] === 'oc-req' || msg[2][1] === 'on-req'))
    )
      ? msg[msg.length - 2]
      : msg[msg.length - 1]

```

**Comment by f3rno** [comment] 2020-02-24 08:02
Duplicate of https://github.com/bitfinexcom/bitfinex-api-node/issues/193

This is a backend error, the packet should have 2 sequence numbers.

**Comment by f3rno** [comment] 2020-02-25 17:46
Closing as duplicate of #193

**Closed by f3rno** 2020-02-25 17:46 UTC
