### ISSUE TITLE
onOrderSnapshot() crash while transform=true

### ISSUE THREAD

**Issue by nedievas** [bitfinexcom/bitfinex-api-node#183] opened 2018-01-07 08:01 UTC
My code:
```
const BFX = require('bitfinex-api-node')

const bfx = new BFX({
  apiKey: 'mykey',
  apiSecret: 'mysecret',

  ws: {
    autoReconnect: true,
    seqAudit: false,
    packetWDDelay: 10 * 1000,
    transform: true
  }
})

const ws = bfx.ws(2)

ws.on('error', (err) => console.log(err))
ws.on('open', () => {
  ws.auth()
})
ws.on('message', (msg) => {
  console.log('msg: %j', msg)
})

ws.once('auth', () => {
  console.log('authenticated')
})

ws.onOrderSnapshot({}, (orders) => {
  var msg = JSON.stringify(orders, null, 2)
  console.log('order snapshot: ', msg)
})

ws.open()
```
when `transform` = **true** I get this error **onOrderSnapshot()**:
```
/home/test/Trader/routes/connect.js:47
  var msg = JSON.stringify(orders, null, 2)
                 ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ws.onOrderSnapshot (/home/test/Trader/routes/connect.js:47:18)
    at listeners.forEach (/home/test/Trader/node_modules/bitfinex-api-node/lib/transports/ws2.js:704:9)
    at Array.forEach (<anonymous>)
    at Function._notifyListenerGroup (/home/test/Trader/node_modules/bitfinex-api-node/lib/transports/ws2.js:698:15)
    at WSv2._propagateMessageToListeners (/home/test/Trader/node_modules/bitfinex-api-node/lib/transports/ws2.js:651:12)
    at WSv2._handleAuthMessage (/home/test/Trader/node_modules/bitfinex-api-node/lib/transports/ws2.js:639:10)
    at WSv2._handleChannelMessage (/home/test/Trader/node_modules/bitfinex-api-node/lib/transports/ws2.js:412:19)
    at WSv2._onWSMessage (/home/test/Trader/node_modules/bitfinex-api-node/lib/transports/ws2.js:377:12)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/home/test/Trader/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/test/Trader/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/test/Trader/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/test/Trader/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/test/Trader/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/test/Trader/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
```
if `transform` = **false**, then it's OK.

**Comment by f3rno** [comment] 2018-01-08 18:07
@nedievas this has to do with the fact that transformed orders receive a reference to the `ws2` client. So when you stringify them, `JSON.stringify` errors out on that field.

I'm closing this as it is not a bug in the library, and not a normal use case. If you need to stringify an object order, delete the `_ws` key with `orders.forEach(o => delete o._ws)`, but keep in mind that it will no longer auto-update.

The addition of the ws client on orders could be made configurable in the future if more people ask for/report this, but for now by default it is assumed you want auto model updates w/ `transform: true`

**Closed by f3rno** 2018-01-08 18:07 UTC
