### ISSUE TITLE
[question] close event triggered after a couple of hours. Code 1006

### ISSUE THREAD

**Issue by samidarko** [bitfinexcom/bitfinex-api-node#154] opened 2017-12-05 16:11 UTC
Hi,

I'm collecting some trade data for 6 pairs using websocket api v2 but the process stops after 1 or 2 hours. The `close` event is triggered. Code 1006.

Is it happening to somebody else?

Thanks by advance

**Comment by f3rno** [comment] 2017-12-11 17:16
Hmm, this sounds similar to the other closed connection issues. As a temporary workaround, can you manually reconnect on close? We have an updated ws v2 coming out shortly which will have this built in.

Closing as duplicate of #112

**Closed by f3rno** 2017-12-11 17:16 UTC

**Comment by jsappme** [comment] 2018-04-09 22:33
@f3rno  any update on this issue, we are all experiencing closing websocket connections after a while that makes this module kind of useless. A fix for this will awesome. Thanks.
