### ISSUE TITLE
Nonce too small error

### ISSUE THREAD

**Issue by denisenkoaj** [bitfinexcom/bitfinex-api-node#111] opened 2017-09-10 21:06 UTC
Hello! Simple function like:

```
    const restws = new BFX(apiKey, apiSecret, opts).rest;

    var response;
    response = restws.wallet_balances(function (err, data) {
        console.log(err);
        console.log(data);
    });
```
returns error like this:

> Error: Nonce is too small.

There is solution:
in rest.js should change:
`this.nonce = Date.now() * 1000`

just try it.

**Comment by androng** [comment] 2017-09-15 02:15
I still get this error when using both websocket and REST. I tried your fix and even submitted a pull request here but it does not work unless you use REST only. https://github.com/bitfinexcom/bitfinex-api-node/pull/100

This is annoying--I think I will have to use the workaround mentioned in that pull request where I use TWO API keys.

**Comment by robertkowalski** [comment] 2017-09-15 08:09
hi @denisenkoaj,

thank you for the report.

i reproduced the issue and talking with the team right how we can still provide a secure API and also increase the usability.

the nonces are used to guard users network attacks so we have to be careful here.

**Comment by robertkowalski** [comment] 2017-09-15 08:31
in the meantime i documented the status quo and improved the error messages: https://github.com/bitfinexcom/bitfinex-api-node/pull/118

**Comment by f3rno** [comment] 2018-01-02 19:41
Closing as duplicate of https://github.com/bitfinexcom/bitfinex-api-node/issues/116

**Closed by f3rno** 2018-01-02 19:41 UTC
